# server端口配置  
server:
  port: 8080
  
info:
  component: Ecshop product Service

# endpoint 配置
endpoints:
    restart:
        id: restart
        sensitive: true
        enabled: true
    shutdown:
        id: shutdown
        enabled: true

# 日志配置          
logging:
  level:
    root: INFO
    
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://10.100.15.176:8761/eureka/

# Spring及数据库相关配置     
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://10.100.15.170:33316/newshop_test?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: xhbs_ec_test
    password: 32d23dswed23d23d23
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 25
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x'
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: false
    filters: stat    
  jpa:
    show-sql: true

---
# 针对于部署到生产环境.
spring:
  profiles: pro
  rabbitmq:
    addresses: 10.1.2.113
  datasource:
    url: jdbc:mysql://10.1.2.49:33306/newshop?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: xhbs_website
    password: 32rdf23f23fd23r32r32
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 25
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x'
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: false
    filters: stat    
  jpa:
    show-sql: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          region:
            factory_class: org.hibernate.cache.redis.RedisRegionFactory
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.2.113:8761/eureka/